image: ruby:3.0



before_script:
  - ruby -v
  - which ruby
  - gem install bundler
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop
