require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.2

Style/AsciiComments:
  Exclude:
    - 'lib/music_composition/notation/note.rb'

RSpec/ExampleLength:
    Max: 20

RSpec/MultipleExpectations:
  Max: 25

RSpec/DescribedClass:
  Exclude:
    - 'spec/music_composition/version_spec.rb'

RSpec/FilePath:
  Exclude:
    - 'spec/music_composition/note_letter_spec.rb'
    - 'spec/music_composition/note_quality_spec.rb'
    - 'spec/music_composition/duration_type_spec.rb'
    - 'spec/music_composition/duration_value_spec.rb'
    - 'spec/music_composition/interval_quality_spec.rb'
    - 'spec/music_composition/measure_type_spec.rb'
    - 'spec/music_composition/scale_pattern_spec.rb'


Metrics/LineLength:
  Exclude:
    - 'music_composition.gemspec'

Style/Copyright:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/DocumentationMethod:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

