# This is the configuration used to check the rubocop source code.

#inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.1

Metrics/AbcSize:
    Max: 18

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'music_composition.gemspec'

Metrics/PerceivedComplexity:
  Max: 8

Style/ConstantName:
  Exclude:
    - 'spec/music_composition/defines/pitch_defines.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/Encoding:
  EnforcedStyle: always
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

