# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.1



Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'music_theory.gemspec'


Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/Encoding:
  EnforcedStyle: always
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

