# This is the configuration used to check the rubocop source code.

require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.1

Style/AsciiComments:
  Exclude:
    - 'lib/music_composition/notation/note.rb'

RSpec/ExampleLength:
    Max: 27

RSpec/MultipleExpectations:
  Max: 28

RSpec/DescribedClass:
  Exclude:
    - 'spec/music_composition/version_spec.rb'


RSpec/FilePath:
  Exclude:
    - 'spec/music_composition/note_letter_spec.rb'
    - 'spec/music_composition/note_quality_spec.rb'
    - 'spec/music_composition/duration_type_spec.rb'
    - 'spec/music_composition/duration_value_spec.rb'
    - 'spec/music_composition/interval_quality_spec.rb'
    - 'spec/music_composition/measure_type_spec.rb'
    - 'spec/music_composition/scale_pattern_spec.rb'


Metrics/LineLength:
  Exclude:
    - 'spec/music_composition/**/*'
    - 'music_composition.gemspec'


Style/ConstantName:
  Exclude:
    - 'spec/music_composition/defines/pitch_defines.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/Encoding:
  EnforcedStyle: always
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

